pipeline {
    agent {
        docker { image 'butroskali/robo_python' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'invoke  robot'
            }
        }
    }
}